from aiogram.filters import Command
#команди
START_COMMAND=Command("start")
DELETE_COMMAND=Command("delete_book")
DETECTIVES_COMMAND=Command("detectives")
ROMANCE_COMMAND=Command("romance")
FANTASY_COMMAND=Command("fantasy")
FICTION_COMMAND=Command("fiction")
HORROR_COMMAND=Command("horror")
COMICS_COMMAND=Command("comics")
POETRY_COMMAND=Command("poetry")
WAR_PROSE_COMMAND=Command("war_prose")
HISTORICAL_NOVELS_COMMAND=Command("historical_novels")
WOMEN_PROSE_COMMAND=Command("women_prose")
NON_FICTION_COMMAND=Command("non_fiction")
ESOTERICS_COMMAND=Command("esoterics")
#прочитані книги
READ_COMMAND = Command("read")
MY_READS_COMMAND = Command("my_reads")
#команди для створення
BOOK_DETECTIVE_CREATE_COMMAND=Command("book_detective_create")
BOOK_ROMANCE_CREATE_COMMAND=Command("book_romance_create")
BOOK_FANTASY_CREATE_COMMAND=Command("book_fantasy_create")
BOOK_FICTION_CREATE_COMMAND=Command("book_fiction_create")
BOOK_HORROR_CREATE_COMMAND=Command("book_horror_create")
BOOK_COMICS_CREATE_COMMAND=Command("book_comics_create")
BOOK_POETRY_CREATE_COMMAND=Command("book_poetry_create")
BOOK_HISTORICAL_NOVELS_CREATE_COMMAND=Command("book_historical_novels_create")
BOOK_WAR_PROSE_CREATE_COMMAND=Command("book_war_prose_create")
BOOK_WOMEN_PROSE_CREATE_COMMAND=Command("book_women_prose_create")
BOOK_NON_FICTION_CREATE_COMMAND=Command("book_non_fiction_create")
BOOK_ESOTERICS_CREATE_COMMAND=Command("book_esoterics_create")